version: '3.7'
services:
  inbox:
    container_name: inbox_service
    image: inbox
    build:
      context: ./ssh
    ports:
      - "20:22"
    volumes:
      - type: volume
        source: inbox_folder
        target: /inbox
    restart: always
    networks:
      - inboxnet

  baikonur:
    container_name: baikonur_service
    restart: always
    image: baikonur
    build:
      context: ./baikonur
    volumes:
      - type: volume
        source: inbox_folder
        target: /srv/autobuildinbox
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
    networks:
      autobuildnet:
        aliases:
          - baikonur
    secrets:
      - jenkins-user
      - jenkins-pass


  jenkins:
    container_name: jenkins_service
    image: autobuild_jenkins
    build:
      context: jenkins
    ports:
      - "443:8080"
    volumes:
      - type: volume
        source: jenkins_config
        target: /var/jenkins_home
    restart: always
    networks:
      autobuildnet:
        aliases:
          - jenkins_service 
    secrets:
      - jenkins-user
      - jenkins-pass

  repobuilder:
    container_name: repobuilder_service
    image: repobuilder
    restart: always
    build:
      context: .
      dockerfile: repobuilder/Dockerfile
    volumes:
      - type: volume
        source: repository
        target: /srv/repository
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
    networks:
      autobuildnet:
        aliases:
          - repobuilder_service
  web:
    container_name: webrepo_service
    image: httpd:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: repository
        target: /usr/local/apache2/htdocs/
      - type: volume
        source: logs_folder
        target: /usr/local/apache2/htdocs/buildlogs/
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
    networks:
      webnet:
        aliases:
          - webrepo
  sbuild_1:
    container_name: sbuild_1_service
    image: sbuild_lliurex19
    build:
      context: .
      dockerfile: sbuild/Dockerfile
    restart: always
    volumes:
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
      - type: volume
        source: logs_folder
        target: /buildlogs/
    networks:
      webnet:
        aliases:
          - sbuild_1
      autobuildnet:
        aliases:
          - sbuild_1

  sbuild_2:
    container_name: sbuild_2_service
    image: sbuild_lliurex19
    build:
      context: .
      dockerfile: sbuild/Dockerfile
    restart: always
    volumes:
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
      - type: volume
        source: logs_folder
        target: /buildlogs/
    networks:
      webnet:
        aliases:
          - sbuild_2
      autobuildnet:
        aliases:
          - sbuild_2

  sbuild_3:
    container_name: sbuild_3_service
    image: sbuild_lliurex19
    build:
      context: .
      dockerfile: sbuild/Dockerfile
    restart: always
    volumes:
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
      - type: volume
        source: logs_folder
        target: /buildlogs/
    networks:
      webnet:
        aliases:
          - sbuild_3
      autobuildnet:
        aliases:
          - sbuild_3

  sbuild_4:
    container_name: sbuild_4_service
    image: sbuild_lliurex19
    build:
      context: .
      dockerfile: sbuild/Dockerfile
    restart: always
    volumes:
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
      - type: volume
        source: logs_folder
        target: /buildlogs/
    networks:
      webnet:
        aliases:
          - sbuild_4
      autobuildnet:
        aliases:
          - sbuild_4

volumes:
  jenkins_config:
  inbox_folder:
  build_folder:
  logs_folder:
  repository:
networks:
  inboxnet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/30"
  autobuildnet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/28"
  webnet:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/29"
secrets:
  jenkins-user:
    file: ./jenkins_user
  jenkins-pass:
    file: ./jenkins_pass