version: '3.7'
services:
  baikonur:
    container_name: baikonur_service
    tty: true
    restart: always
    image: baikonur
    build:
      context: ./baikonur
    volumes:
      - type: volume
        source: inbox_folder
        target: /srv/autobuildinbox
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
    networks:
      autobuildnet:
        aliases:
          - baikonur
    secrets:
      - jenkins-user
      - jenkins-pass


  jenkins:
    container_name: jenkins_service
    image: autobuild_jenkins
    build:
      context: jenkins
    ports:
      - "443:8080"
    volumes:
      - type: volume
        source: jenkins_config
        target: /var/jenkins_home
    restart: always
    environment:
      - TZ=Europe/Madrid
    networks:
      autobuildnet:
        aliases:
          - jenkins_service 
    secrets:
      - jenkins-user
      - jenkins-pass

  repobuilder:
    container_name: repobuilder_service
    image: repobuilder
    restart: always
    build:
      context: .
      dockerfile: repobuilder/Dockerfile
    volumes:
      - type: volume
        source: repository
        target: /srv/repository
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
    networks:
      autobuildnet:
        aliases:
          - repobuilder_service
  web:
    container_name: webrepo_service
    restart: always
    image: webserver
    build:
      context: .
      dockerfile: web/Dockerfile
    ports:
      - "80:80"
    volumes:
      - type: volume
        source: repository
        target: /usr/share/nginx/html
      - type: volume
        source: logs_folder
        target: /usr/share/nginx/html/buildlogs/
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
    networks:
      webnet:
        aliases:
          - webrepo
  
  packagesfinder:
    container_name: packages_service
    image: packages
    restart: always
    image: packages
    build:
      context: packages
    networks:
      webnet:
        aliases:
          - packages
          - find
          - build
    secrets:
      - packagesconfig
    
    volumes:
      - type: volume
        source: repository
        target: /app/environment/
        read_only: true
      - type: volume
        source: inbox_folder
        target: /srv/autobuildinbox

  sbuild_1:
    container_name: sbuild_1_service
    image: sbuild_lliurex23
    build:
      context: .
      dockerfile: sbuild/Dockerfile
    restart: always
    privileged: true
    secrets:
      - telegram-token
      - telegram-chat-id
    volumes:
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
      - type: volume
        source: logs_folder
        target: /buildlogs/
    networks:
      webnet:
        aliases:
          - sbuild_1
      autobuildnet:
        aliases:
          - sbuild_1

  sbuild_2:
    container_name: sbuild_2_service
    image: sbuild_lliurex23
    build:
      context: .
      dockerfile: sbuild/Dockerfile
    restart: always
    privileged: true
    secrets:
      - telegram-token
      - telegram-chat-id
    volumes:
      - type: volume
        source: build_folder
        target: /srv/autobuildfolder
      - type: volume
        source: logs_folder
        target: /buildlogs/
    networks:
      webnet:
        aliases:
          - sbuild_2
      autobuildnet:
        aliases:
          - sbuild_2

volumes:
  jenkins_config:
  inbox_folder:
  build_folder:
  logs_folder:
  repository:
networks:
  inboxnet:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/30"
  autobuildnet:
    ipam:
      driver: default
      config:
        - subnet: "10.0.1.0/28"
  webnet:
    ipam:
      driver: default
      config:
        - subnet: "10.0.2.0/28"
secrets:
  jenkins-user:
    file: secrets/jenkins_user
  jenkins-pass:
    file: secrets/jenkins_pass
  telegram-token:
    file: secrets/telegram_token
  telegram-chat-id:
    file: secrets/telegram_chat_id
  packagesconfig:
    file: secerts/packagesconfig
