#!/bin/bash
mkdir /srv/repository || true
for x in $(ls /usr/share/baikonur); do
    if [ ! -d $x ]; then
        cp -r /usr/share/baikonur/$x /srv/repository/
        chmod -R g+s /srv/repository/$x
        chown -R :www-data /srv/repository/$x
    fi
done

find /srv/repository/baikonur -iname unstable -exec bash -c 'cd $0; reprepro -v export' {} \;
/usr/bin/celery -A worker.celery worker -Q "repobuilder"
