FROM jenkins/jenkins:lts-jdk17
 
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
 
#COPY security.groovy /usr/share/jenkins/ref/init.groovy.d/security.groovy
 
#COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
#COPY configs /usr/share/baikonur/
#RUN /bin/jenkins-plugin-cli -f /usr/share/jenkins/ref/plugins.txt
