#!/usr/bin/env python3
import sys

def run():
    z = sys.argv[1]
    first = z.split(":")
    if len(first) > 1:
        second = first[1]
    else:
        second = first[0]
    list_version = second.split("-")[0:-1]
    if len(list_version) > 0:
        print('-'.join(list_version))
    else:
        print(second)


if __name__ == '__main__':
	run()
