#!/usr/bin/env python3
import deb822
import sys
import codecs
changes = deb822.Changes(codecs.open(sys.argv[1],encoding='utf-8'))
if changes['Distribution'].startswith('bionic'):
    print('lliurex19')
elif changes['Distribution'].startswith('focal'):
    print('lliurex21')
elif changes['Distribution'].startswith('lliurex22'):
    print('lliurex22')
elif changes['Distribution'].startswith('jammy'):
    print('lliurex23')
else:
    sys.exit(1)
